# Generated by Django 2.2 on 2019-04-26 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codexamen', models.CharField(max_length=10, unique=True)),
                ('fechacreacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('orden', models.IntegerField(null=True)),
                ('ponderacion', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('documento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Puntaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.Categoria')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.Nivel')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.Categoria')),
                ('nivel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.Nivel')),
            ],
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('es_correcto', models.BooleanField(default=False)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.Pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='ExamenPregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.FloatField(null=True)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.Examen')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.Pregunta')),
                ('respuesta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.Opcion')),
            ],
            options={
                'db_table': 'cuestionario_examen_pregunta',
            },
        ),
        migrations.AddField(
            model_name='examen',
            name='nivel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.Nivel'),
        ),
        migrations.AddField(
            model_name='examen',
            name='participante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.Participante'),
        ),
    ]
