# Generated by Django 2.2 on 2019-04-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntaje',
            name='puntaje',
            field=models.IntegerField(null=True),
        ),
    ]
