# Generated by Django 2.0.13 on 2019-04-08 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen_pregunta',
            name='respuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.Opcion'),
        ),
    ]
