# Generated by Django 2.0.13 on 2019-04-08 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0002_auto_20190408_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen_pregunta',
            name='respuesta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.Opcion'),
        ),
    ]
